export const assamese = {
    dashboard: { 
        welcome: "স্বাগতম",
        ca: "গ্ৰাহক",
        number: "ন",
        lastMonthConsumption: "যোৱা মাহত সৰ্বমুঠ ব্যৱহাৰ",
        monthlyConsumption: "মাহিলি ব্যৱহাৰ",
        monthlyForecast: "মাহিলি পূৰ্বানুমান",
        today: "দৈনিক",
        week: "এই সপ্তাহ",
        month: "এই মাহ",
        graphButton: "(মান নিৰীক্ষণ কৰিবলৈ ৰেখাচিত্ৰত ক্লিক কৰক।)",
        yourConsumption: "আপোনাৰ বিদ্যুৎ-ব্যৱহাৰ",
        units: "ইউনিট"
    },
    comparison: {
        unit: "ব্যৱহাৰৰ",
        comparison: "তুলনা",
        headerContext: "বিদ্যুৎ ব্যৱহাৰৰ ওপৰত নিয়ন্ত্ৰণ ৰাখিবলৈ আপোনাৰ দৈনিক, সাপ্তাহিক আৰু মাহিলি বিদ্যুৎ ব্যৱহাৰৰ তুলনা কৰক।",
        today: "আজি ",
        inProgress: "চলিত",
        consumption: "ব্যৱহাৰ",
        yesterday: "যোৱাকালি",
        weekly: "সাপ্তাহিক ব্যৱহাৰৰ",
        comparison: "তুলনা",
        graphButton: "(সবিশেষ জানিবলৈ ৰেখাচিত্ৰত ক্লিক কৰক।)",
        lable1: "যোৱা সপ্তাহ ব্যৱহাৰ (ইউনিট)",
        lable2: "এই সপ্তাহ ব্যৱহাৰ (ইউনিট)",
        monthly: "মাহিলি ব্যৱহাৰৰ ",
        units: "ইউনিট"
    },
    history: {
        header: "পূৰ্বৰ বিদ্যুৎ ব্যৱহাৰ",
        headerContext: "আপোনাৰ নখদৰ্পনত পূৰ্বৰ বিদ্যুৎ ব্যৱহাৰৰ বিষয়ে বিশদ ",
        custom: "কাষ্টম",
        start: 'স্টার্ট',
        date: 'ডেট',
        end: 'এন্ড',
        startDate: "আৰম্ভণি তাৰিখ",
        endDate: "সমাপ্তিৰ তাৰিখ",
        legend: "টোকা: অনুগ্ৰহ কৰি 01-31 দিনৰ পৰা অন্তিম তাৰিখ বাছনি কৰক",
        submit: "দাখিল কৰক",
        customLegend: "X-অক্ষ সময়  আৰু Y-অক্ষ ব্যৱহাৰ",
        today: " দৈনিক",
        week: "সপ্তাহ",
        month: "মাহ",
        year:"বছৰ",
        legend1: "X-অক্ষ সময় আৰু Y-অক্ষ ব্যৱহাৰ",
        legend2: "X-অক্ষ দিনসমূহ আৰু Y-অক্ষ ব্যৱহাৰ",
        legend3: "X-অক্ষ মাহ আৰু Y-অক্ষ ব্যৱহাৰ",
        legend4: "X-অক্ষ বছৰ আৰু Y-অক্ষ ব্যৱহাৰ",
        graphButton: "(মান নিৰীক্ষণ কৰিবলৈ ৰেখাচিত্ৰত ক্লিক কৰক।)",
        total: "সৰ্বমুঠ",
        consumption: "ব্যৱহাৰ",
        average: "গড়",
        units: "ইউনিট",
        noRecordsFound: "কোনো ৰেকৰ্ড পোৱা নগ'ল",
        loading: "লোড কৰা হৈছে",
    },
    prepaidBalance: {
        prepaid: "প্ৰি-পেইদ্ ",
        balance: "জমাৰাশি",
        headerContext: "আপোনাৰ বিল নিৰীক্ষণ কৰি অন্‌লাইন পৰিশোধ কৰক।",
        current: "বৰ্তমান",
        history: "পূৰ্বৰ ৰিচাৰ্জ সমূহ",
        medium: "মধ্যম",
        low: "নিম্ন",
        high: "উচ্চ",
        amount: "জমাৰাশি",
        date: "তাৰিখ",
        button: "টপ্‌-আপ কৰিবলৈ ইয়াত ক্লিক কৰক।"
    },
    postpaidBalance: {
        postpaid: "পোষ্টপেইদ্‌",
        balance: "অনাদায়",
        headerContext: "আপোনাৰ বিল নিৰীক্ষণ কৰি অন্‌লাইন পৰিশোধ কৰক।",
        amount: "বিলৰ পৰিমাণ",
        consumption: "ইউনিট ব্যৱহাৰ",
        units: "ইউনিট",
        billNumber: "বিল ন",
        ca: "গ্ৰাহক",
        number: "ন",
        billGenerationDate: "বিল প্ৰস্তুতকৰণৰ তাৰিখ",
        billPaybyDate: "বিল এই তাৰিখৰ আগতে পৰিশোধ কৰিব লাগিব",
        clickHereToPay: "পৰিশোধ কৰিবলৈ ইয়াত ক্লিক কৰক।"
    },
    mdi: {
        maximum: "সৰ্বোচ্চ",
        demand: "দিমাণ্ড",
        maxDemand: "মাহিলি দিমাণ্ড",
        headerContext: "আপুনি অনুমোদিত দিমাণ্ডতকৈ অধিক ব্যৱহাৰ কৰিছে নেকি?",
        sanctioned: "অনুমোদিত ",
        load: "লোড",
        units: "কি: ৱাট্",
        monthly: "সৰ্বোচ্চ",
        barGraphInfo: "(মান নিৰীক্ষণ কৰিবলৈ ৰেখাচিত্ৰত ক্লিক কৰক।)",
        legend: "মাহিলি সৰ্বোচ্চ দিমাণ্ড নিদশক",
        graphButton: "এই মাহৰ MDI চাৰ্ট  চাবলৈ ইয়াত ক্লিক কৰক।",
        recorded: "ৰেকৰ্ডেদ",
        spikeMd: "স্পাইক MD(সৰ্বোচ্চ দিমাণ্ড)",
        logDate: "লগ হোৱা সময়",
        pmd: "P-MD",
        amd: "A-MD",
        voltage: "ভ'ল্টেজ্",
        tableFooter: "এ-এম ডি - নিৰ্ধাৰিত এম ডি, প-এম ডি - শীৰ্ষ এম ডি",
        // Horizontal Graph
        maximumDemandReached: 'ম্যাক্সিমাম ডিমান্ড রেযাচ্ছেদ (কিউ)',
        assignedMaximumDemand: 'নিৰ্ধাৰিত সৰ্বোচ্চ দিমাণ্ড',
    },
    powerQuality: {
        power: "শক্তিৰ",
        quality: "গুণগত মান",
        headerContext: "আপুনি পাই থকা শক্তিৰ গুণগত মান কেনেকুৱা?",
        peak: "শীৰ্ষ ",
        voltage: "ভ'ল্টেজ্‌",
        hourlyTrend: "প্ৰতিঘণ্টাৰ ট্ৰেণ্ড",
        legend: "যোৱা 7 ঘণ্টাত ভ'ল্টেজৰ উত্থান",
        dataTable: "তথ্য-তালিকা",
        graph: "ৰেখাচিত্ৰ",
        logHour: "লগ হোৱা সময়",
        freq: "ফ্ৰিক:",
        md: "এম.ডি",
        tableFooter: "এম.ডি - সৰ্বোচ্চ দিমাণ্ড, ফ্ৰিক: - ফ্ৰিকুয়েন্চী"
    },
    eventAnalysis: {
        event: "সংঘটনাৰ",
        analysis: "বিশ্লেষণ",
        headerContext: "আপোনাৰ স্মাৰ্ট মিটাৰে শক্তিৰ গুণাগুণ সম্পৰ্কীয় সংঘটনা চিনাক্ত কৰিব পাৰে।",
        selectParameter: "বাছনি কৰক",
        category: "শ্ৰেণী",
        make: "বাছনি",
        selection: "কৰক",
        daily: "দৈনিক",
        monthly: "মাহিলি",
        yearly: "বাৰ্ষিক",
        month: "মাহ",
        year: "বছৰ",
        period: "সময়ৰ ",
        duration: "অন্তৰাল",
        startDate: "আৰম্ভণি তাৰিখ",
        endDate: "সমাপ্তিৰ তাৰিখ",
        submit: "দাখিল কৰক",
        cancel: "বাতিল কৰা",
        recorded: "নথিভুক্ত",
        events: "সংঘটনসমূহ",
        date: "তাৰিখ",
        eventName: "সংঘটনা ক্ৰমাংক",
        count: "গণনা",
        voltage: "ভ'ল্টেজ",
        loadingDropdown: "ড্ৰপডাউন লোড কৰা হৈছে",
        loading: "লোড কৰা হৈছে",
    },
    energyTips: {
        energy: "শক্তি",
        savingsTips: "সংৰক্ষণৰ আভাস",
        tip: "টিপ",
        headerContext: "সাধাৰণ কিছুমান পদ্ধতিয়ে আপোনাক ব্যাপক শক্তি সংৰক্ষণত সহায় কৰিব পাৰে।",
        saving: "সংৰক্ষণৰ দিশা ",
        guidelines: "নিৰ্দেশনা"
    },
    faqs: {
        top: "বহুলভাৱে",
        questions: "সোধা প্ৰশ্নসমূহ",
        haveQueries: "আপোনাৰ কোনো প্ৰশ্ন আছে নেকি?",
        all: "সকলো শ্ৰেণী",
        general: "সাধাৰণ",
        billing: "বিলিং",
        category: "শ্ৰেণী"
    },
    notifications: {
        be: "জাননী",
        notified: "",
        headerContext: "জাননীৰ দ্বাৰা APDCLৰ সৈতে সংযুক্ত হওক।",
        notifications: "জাননী",
        noNotificationMessage: "এই মুহূৰ্তত আপোনাৰ বাবে একো নতুন জাননী নাই। অনুগ্ৰহ কৰি কিছুসময় পিছত পুনৰ চাওক।",
        clear: "ক্লিয়েৰ কৰক"
    },
    energyCostCalc: {
        energy: "শক্তিৰ",
        costCalculator: "খৰচ গণনা",
        headerContext: "নতুন সৰঞ্জাম ব্যৱহাৰ কৰিব? তাৰ শক্তিৰ প্ৰয়োজনৰ বিষয়ে বিশ্লেষণ কৰক।",
        didYouKnow: 'দিদি ইউ কনো ?',
        didYouKnowContent: 'রেফ্রিজারেশন ট্যাক্স 1200 ওটস এ ডে . হোইচ কস্ট 4000 INR পের্ যার ।',
        // Step 1
        fillDetails: "বিৱৰণ দিয়ক।",
        analysis: "বিশ্লেষণ",
        results: "ফলাফল",
        fillThe: "বিৱৰণ",
        details: "দিয়ক",
        product: "সৰঞ্জামৰ",
        category: "শ্ৰেণী",
        select: "চয়ন কৰক",
        productAge: "সৰঞ্জামৰ বয়স",
        greenStartRating: "গ্ৰীণ ষ্টাৰ ৰেটিংগ (যদি প্ৰযোজ্য)*",
        next: "আগলৈ",
        // Step 2
        confirm: "নিশ্চিত কৰক",
        consumption: "ব্যৱহাৰ",
        watts: "ৱাট",
        timeFrame: "সময় সীমা",
        hoursDays: "5 ঘণ্টা/ প্ৰতিদিন",
        rate: "ৰেট*",
        back: "পিছলৈ",
        calculate: "হিচাপ কৰক",
        // Step 3
        daily: "দৈনিক",
        monthly: "মাহে",
        yearly: "বাৰ্ষিক",
        costing: "খৰচ",
        forecasted: "পূৰ্বানুমানিত",
        bill: "বিল",
        month: "মাহে",
        goBack: "পিছলৈ যাওক",
        // Next Screen
        typical: "সাধাৰণ",
        householdAppliance: "ঘৰুৱা সৰঞ্জামবোৰ",
        householdApplianceContent: "আপুনি প্ৰৱেশ কৰিব বিচৰা একাউণ্টটো চয়ন কৰক অথবা আন এটা একাউণ্ট যুক্ত কৰক।",
        clickHere: "অধিক জানিব বিচাৰে? ইয়াত ক্লিক কৰক।>",
        search: "সন্ধান কৰক",
        general: "সাধাৰণ",
        lightning: "তড়িৎ"
    },
    support: {
        header1: "আজি আপোনাক কিদৰে সহায় কৰিব",
        header2: "পাৰোঁ ?",
        search: "সন্ধান কৰক",
        general: "সাধাৰণ",
        category: "শ্ৰেণী",
        image: "ছবি",
        info1 : [
            { name: 'বিল পৰিশোধ', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
            { name: 'আমেৰিকা যুক্তৰাষ্ট্ৰৰ সৈতে যোগাযোগ কৰক', url: require('SmartgasConsumerApp/assets/animations/profile.json') },
            { name: 'আমাৰ বিষয়ে', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
            { name: 'অৱস্থান', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
        ],
        info2 : [
            { name: 'স্মাৰ্ট বিজুলী', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
            { name: 'সেৱা নিৰ্দেশিকা', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
        ],
        info3 : [
            { name: 'লাইভ চেট', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
            { name: 'সংৰক্ষণ', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
        ]
    },
    checkPrograms: {
        search: "সন্ধান কৰক",
        upcomingProgram: "বিষয়ে সন্ধান কৰক",
        headerContext: "শক্তি সংৰক্ষণ কাৰ্যক্ৰম",
        period: "সময়",
        duration: "কালদৈৰ্ঘ্য",
        submit: "দাখিল কৰক",
        program: "কাৰ্যক্ৰমৰ",
        list: "তালিকা",
        secondScreenHeaderContext: "শক্তি সংৰক্ষণ কাৰ্যক্ৰমসমূহ",
        date: "তাৰিখ",
        savings: "সংৰক্ষণ",
        thirdScreenHeaderContext: "আপোনাৰ শক্তি সংৰক্ষণ কাৰ্যক্ৰম",
        episodeInformation: "খণ্ডৰ তথ্",
        eventCategory: "সংঘটনাৰ শ্ৰেণী",
        expectedSavings: "আকাংক্ষিত সংৰক্ষণ",
        startDate: "তাৰিখৰ পৰা",
        endDate: "তাৰিখলৈ",
        duration: "কালদৈৰ্ঘ্য",
        showInterest: "আগ্ৰহ প্ৰকাশ কৰক",
        //Upcomming Events
        thankYouForShowingthe: "দেখুওৱাৰ বাবে আপোনাক ধন্যবাদ",
        interest: "আগ্ৰহ",
    },
    myPrograms: {
        myPrograms: "মোৰ কাৰ্যক্ৰমসমূহ",
        plmdr: "PLMDR",
        headerContext: "আপোনাৰ শক্তি-সংৰক্ষণৰ কাৰ্যক্ৰমসমূহ",
        pastEvents: "অতীতৰ ঘটনাসমূহ",
        upcomingEvents: "উপকমিত ঘটনাসমূহ",
        date: "তাৰিখ",
        savings: "সঞ্চয়",
        search: "Search",
        upcomingProgram: "Upcoming Program",
        headerContext: "Energy saving programs",
        period: "সময়",
        duration: "কালদৈৰ্ঘ্য",
        submit: "দাখিল কৰক",
        program: "কাৰ্যক্ৰমৰ",
        list: "তালিকা",
        secondScreenHeaderContext: "শক্তি সংৰক্ষণ কাৰ্যক্ৰমসমূহ",
        date: "তাৰিখ",
        savings: "সংৰক্ষণ",
        // Past Events
        programCategory: "প্ৰগ্ৰাম শ্ৰেণী",
        pastHeaderContext: "শক্তি দিৱস সংৰক্ষণ কৰক",
        congratulations: "অভিনন্দন",
        youHaveSavedSuccessfully: "আপুনি সফলতাৰে সংৰক্ষণ কৰিছে",
        withThe: "ইয়াৰ সৈতে",
        energySaving: "শক্তি সঞ্চয়",
        event: "ঘটনা",
        youHave: "তোমাৰ আছে",
        succesfully: "সফলতাৰে",
        been: "হৈছে",
        unsubscribed: "সাবস্ক্ৰাইব কৰা হোৱা নাই",
        fromTheEvent: "অনুষ্ঠানৰ পৰা",
        // Upcomming Events
        thirdScreenHeaderContext: "আপোনাৰ শক্তি সংৰক্ষণ কাৰ্যক্ৰম",
        episode: "খণ্ড",
        information: "তথ্য",
        episodeInformation: "খণ্ড তথ্য",
        engerySaving: "শক্তি সঞ্চয়",
        eventCategory: "সংঘটনাৰ শ্ৰেণী",
        mySavings: "মোৰ সঞ্চয়",
        expectedSavings: "আকাংক্ষিত সংৰক্ষণ",
        startDate: "তাৰিখৰ পৰা",
        endDate: "তাৰিখলৈ",
        duration: "কালদৈৰ্ঘ্য",
        noMoreInterest: "এতিয়া আৰু আগ্ৰহী নহয়",
    },
    netMetering: {
        net: "নেট্‌",
        metering: "মিটাৰিং",
        headerContext: "আপোনাৰ সৌৰ-শক্তি তন্ত্ৰৰ পৰা লাভ কৰা পাওনাৰ বিষয়ে জানক।",
        savings: "জমাৰ",
        utilization: "ব্যৱহাৰ",
        today: "আজি",
        week: "সপ্তাহ",
        month: "মাহ",
        apdclInput: "APDCLৰ পৰা পোৱা ইনপূট",
        mySolarOutput: "মোৰ সৌৰ আউটপূট",
        units: "একক"
    },
    schemes: {
        apdcl: "এপিডিচিএল",
        schemes: "আঁচনিসমূহ",
        search: "সন্ধান কৰক",
        headerContext: "অধিক তথ্যৰ বাবে নিৰ্দিষ্ট পৃষ্ঠালৈ যাবলৈ ইয়াত ক্লিক কৰক।",
        copyright: "স্বত্বাধিকাৰ @ 2021 - APDCL"
    },
    settings: {
        settings: "সজ্জা",
        // Profile Settings
        profile: "প্ৰ'ফাইল",
        information: "তথ্য",
        PIContent: "নাম, ই-মেইল, সুৰক্ষা",
        manage: "একাধিক",
        multipleAccount: "একাউণ্ট পৰিচালনা কৰক",
        MMAContent: "একাউণ্ট পৰিচালনা কৰক",
        change: "পাচৱ'ৰ্ড",
        password: "সলনি কৰক",
        CPContent: "আপোনাৰ বৰ্তমান ৰ পাছৱাৰ্ড পৰিবৰ্তন কৰক",
        // App Settings
        app: "এপ্‌",
        color: "ৰং",
        mode: "ৰূপ",
        CMContent: "এপ-ৰ ম'দ লাইট/ডাৰ্ক কৰিবলৈ",
        language: "ভাষা চয়ন কৰক",
        CLContent: "ভাষা সলনি কৰক",
        user: "ব্যৱহাৰকাৰীৰ",
        management: "পৰিচালনা",
        UMContent: "পৰিয়ালৰ সদস্যক যুক্ত কৰিবলৈ",
        // General Settings
        general: "সাধাৰণ",
        rateOur: "এই এপ- ক ৰেটিং প্ৰদান কৰক",
        ROAContent: "এই এপ-ক ৰেটিং আৰু ৰিভিউ প্ৰদান কৰক",
        send: "ফিদবেক",
        feedback: "প্ৰেৰণ কৰক",
        SFContent: "APDCL-লৈ আপোনাৰ মনৰ কথা প্ৰেৰণ কৰক",
        terms: "চৰ্তাৱলী",
        conditions: "",
        TCContent: "আমাৰ গোপনীয়তাৰ নীতি আৰু চৰ্তাৱলী সম্পৰ্কে জানক"
    },
    profile: {
        sanctionedLoad: "অনুমোদিত লোদ",
        serviceDate: "সেৱাৰ তাৰিখ",
        merterServiceNumber: "মিটাৰ্ নঃ",
        contactNumber: "যোগাযোগ নম্বৰ",
        emailId: "ই-মেইল",
        caNo: "গ্ৰাহক নঃ",
    },
    multipleAccounts: {
        manage: "একাধিক",
        multipleAccounts: "একাউণ্ট পৰিচালনা কৰক",
        headerContext: "একেটা মোবাইল নম্বৰৰ সৈতে সংযুক্ত আপোনাৰ আন একাউণ্টবোৰ ইয়াত যুক্ত কৰক।",
        listOf: "পৰিচালিত",
        accountsHandled: "একাউণ্টৰ তালিকা",
        slNo: "ক্ৰমিক নং",
        name: "নাম",
        caNo: "গ্ৰাহক ক্ৰমাংক",
        action: "কাৰ্য",
        tableFooter: "আপুনি 20 টালৈ একাউণ্ট সংযুক্ত কৰিব পাৰে",
        // Switch
        switchAccount: "একাওন্ট পৰিবৰ্তন কৰক",
        switchAccountMessage: "আপুনি একাউণ্টব্যৱহাৰকাৰীলৈ সলনি কৰিব বিচাৰে নেকি",
        ok: "হ'ব",
        cancel: "বাতিল কৰা",
        // Delete
        deleteHeader: "একাওন্ট মচি পেলাওক",
        deleteMessage: "আপুনি ব্যৱহাৰকাৰীলৈ একাউণ্ট বিলোপ কৰিব বিচাৰে নেকি",
        deleteSuccess: "একাওন্ট সফলতাৰে বিলোপ কৰা হৈছে",
        // Create
        createHeader: "তথ্য",
        createMessage: "চিএ নম্বৰৰ সৈতে যোগ কৰা সদস্য",
        createSuccessfully: "সফলতাৰে",
        // Swtich Account Messages
        message1: "একাউণ্ট চুইচ আৰম্ভ কৰা হৈছে...।",
        message2: "পৰিবৰ্তন কৰা হৈছে",
        message3: "চূড়ান্ত কৰা হৈছে...।",
        message4: "সতেজ কৰা এপ্লিকেচন...।",
        generateOtp: "জেনেৰেট কৰক অ টি পি",
        consumerNumber: "গ্ৰাহক ন",
        consumer: "গ্ৰাহক",
        number: "ন",
        enter: "প্ৰবিষ্ট কৰক",
        mobileNumber: "মোবাইল নম্বৰ",
        submit: "দাখিল কৰক",
        otp: "অ টি পি"
    },
    changePassword: {
        reset: "পাচৱ'ৰ্দ",
        caNo: "গ্ৰাহক ন",
        password: "ৰি-চেট কৰক।",
        headerContext: "আপোনাৰ একাউণ্টৰ সুৰক্ষা আৰু নিৰাপত্তাৰ বাবে প্ৰতি তিনি মাহৰ অন্তৰালত পাচৱ'ৰ্দ সলনি কৰক।",
        currentPassword: "বৰ্তমানৰ পাচৱ'ৰ্দ",
        newPassword: "নতুন পাচৱ'ৰ্দ",
        confirmPassword: "পাচৱ'ৰ্দ নিশ্চিত কৰক",
        submit: "দাখিল কৰক"
    },
    colorMode: {
        change: "ৰং-ৰূপ",
        colorMode: "সলনি",
        headerContext: "আপোনাৰ ইচ্ছা অনুযায়ী ডাৰ্ক আৰু লাইট্ ম'দৰ মাজত ৰং-ৰূপ সলনি কৰক",
        lightMode: "লাইট্ ম'দ",
        info: "সলনি কৰিবলৈ বাটনটোত ক্লিক কৰক",
        darkMode: "ডাৰ্ক ম'দ",
        message1: "ৰং-ৰুপ সলনি প্ৰক্ৰিয়া আৰম্ভ....",
        changeToDarkMode: "ডাৰ্ক ম'দলৈ সলনি",
        changeToLightMode: "লাইট্ ম'দলৈ সলনি",
        message3: "পৰিসমাপ্তি....",
        message4: "ৰূপান্তৰিত ",
    },
    language: {
        change: "ভাষা সলনি",
        language: "কৰক",
        languageType: "অসমীয়া",
        headerContext: "এপ-টো চলাবলৈ অসমীয়া অথবা ইংৰাজী ভাষা চয়ন কৰক।",
        selectedLanguage: "ভাষা চয়ন কৰক", //selectedLanguage: "ভাষা চয়ন কৰক",
        chooseLanguage: "Select Language",
        message1: "ভাষা আৰম্ভ কৰা হৈছে....",
        message2: "নতুন ভাষা সংস্থাপন কৰা হৈছে....",
        message3: "চূড়ান্ত কৰা হৈছে....",
        message4: "সতেজ কৰা প্ৰয়োগ",
    },
    userManagement: {
        user: "ব্যৱহাৰকাৰীৰ",
        management: "পৰিচালনা",
        headerContext: "আপুনি আপোনাৰ পৰিয়ালৰ সদস্যৰ সৈতে নিয়নত্ৰীত ভাবে আপোনাৰ একাউণ্ট ভাগ-বতৰা কৰিব পাৰে।",
        listOf: "সদস্যসকলৰ",
        members: "তালিকা",
        name: "নাম",
        contactNo: "যোগাযোগ নম্বৰ",
        link: "লিংক",
        action: "কাৰ্য",
        tableFooter: "আপুনি 5 গৰাকী পৰ্যন্ত পৰিয়ালৰ সদস্যক যুক্ত কৰিব পাৰে",
        fillDetails: "বিৱৰণখিনি পুৰ কৰক।",
        analysis: "বিশ্লেষণ",
        results: "ফলাফল",
        // Step 1
        fillThe: "বিৱৰণখিনি পুৰ কৰক।",
        details: "",
        name: "নাম",
        contactNumber: "যোগাযোগ",
        mobileNumberError: "অনুগ্ৰহ কৰি সঠিক মোবাইল নম্বৰ প্ৰদান কৰক।",
        relation: "সম্পৰ্ক", // সম্পৰ্ক চয়ন কৰক।
        select: "চয়ন কৰক",
        master: "মূৰব্বী",
        family: "পৰিয়াল",
        tenant: "ভাৰাতীয়া",
        next: "আগলৈ",
        // Step 2
        confirmThe: "বিৱৰণখিনি নিশ্চিত কৰক|",
        back: "পিছলৈ",
        // Step 3
        sendThe: "প্ৰেৰণ কৰক",
        invitationLink: "নিমন্ত্ৰণ লিংক",
        feedbackContext: "হেই, এপ্পটো চমৎকাৰ..। বিশেষকৈ ডিজাইন",
        send: "প্ৰেৰণ কৰক",
        congratulations: "অভিনন্দন",
        inviteInfo: "লৈ আপোনাৰ নিমন্ত্ৰণ সফলভাৱে প্ৰেৰণ কৰা হ'ল।",
        inviteFooter: "অতিৰিক্ত নিৰ্দেশনাৰ বাবে www.apdcl.org লৈ যাওক।",
        done: "সম্পন্ন"
    },
    feedback: {
        speakYour: "আপোনাৰ মনৰ কথাখিনি ব্যক্ত কৰক।",
        mind: "",
        // headerContext: "Please provide us your Review, for us to serve you better.", // headerContext: "অনুগ্ৰহ কৰি আপোনাৰ সমীক্ষা প্ৰদান কৰক, ই আপোনাক ভালদৰে সেৱা আগবঢ়োৱাত আমাক সহায় কৰিব.",
        headerContext: "অধিক মনোগ্ৰাহী সেৱাৰ বাবে, অনুগ্ৰহ কৰি আপোনাৰ পৰ্যবেক্ষণ দাঙি ধৰক।",
        // Step 1
        howWasYour: "আপোনাৰ অভিজ্ঞতা সম্বন্ধে জনাওক।",
        experience: "",
        next: "আগলৈ",
        sad: "অসন্তুষ্ট",
        neutral: "নিৰপেক্ষ",
        happy: "সুখী",
        // Step 2
        whatMadeYou: "আপুনি কি কাৰণে",
        // questionAnswer: "",
        happyoption1: "তথ্যৰ স্বচ্ছতা",
        happyoption2: "উজু নেভিগেশ্যন",
        happyoption3: "সামগ্ৰিক ৰেহ-ৰূপ",
        back: "পিছলৈ",
        // Step 3
        feedback: "আপোনাৰ মতামত 200 তকৈ কম শব্দত লিখক|",
        submit: "দাখিল কৰক",
        thankYouForSharing: "আপোনাৰ অভিজ্ঞতাৰ বিষয়ে আমাক ",
        your: "জনোৱাৰ বাবে ধন্যবাদ।",
        thanksFooter: "অধিক জানিবৰ বাবে SBPDCL.co ৱেবচাইট চাব পাৰে।",
        footer: "এ.পি.ডি.চি.এল.-ৰ দ্বাৰা এক স্মাৰ্ট প্ৰচেষ্টা।"
    },
    termsAndConditions: {
        termsAnd: "চৰ্তাৱলী",
        conditions: "",
        general: "সাধাৰণ",
        information: "তথ্য", 
        data: "তথ্য",
        source: "উৎসসমূহ"
    },
    contactUs: {
        getIn: "যোগাযোগৰ ",
        touch: "বাবে ",
        headerContext: "আপোনাৰ প্ৰশ্নবোৰ সমাধান কৰিবলৈ এ.পি.ডি.চি.এলৰ সৈতে যোগাযোগ কৰক।.",
        customerCare: "গ্ৰাহক সেৱা",
        emailId: "ই-মেইল আইডি",
        website: "ৱেবছাইট",
        socialMedia: "সামাজিক মাধ্যম",
        footer: "এপিডিচিএল সকলো প্ৰতিলিপি অধিকাৰ সংৰক্ষিত"
    },
    drawer: {
        caNo: "গ্ৰাহক ন",
        logout: "লগ্‌-আউট"
    },
    logout: {
        alert: "সতৰ্কীকৰণ",
        message: "আপুনি নিশ্চিতভাৱে লগ্‌-আউট হ'ব বিচাৰে নে?",
        yes: "হয়",
        no: "নহয়"
    },
    back: "পিছলৈ",
    connectivityHeader: 'কোনো ইণ্টাৰনেট সংযোগ চিনাক্ত কৰা হোৱা নাই.',
    connectivitybody1: 'অনুগ্ৰহ কৰি আপোনাৰ নেটৱৰ্ক পৰীক্ষা কৰক',
    connectivitybody2: 'ছেটিংছ আৰু পুনৰ চেষ্টা কৰক।',
}


