export const english = {
    dashboard: { 
        welcome: "Welcome to Smartgas Connect",
        ca: "Consumer",
        number: "ID",
        dashboardConsumption:{

            lastMonth: "Last Month Consumption",
            currentMonth: "Monthly Consumption",
            nextMonth: "Monthly Forecast"
        },
        today: "Today",
        week: "Week",
        month: "Month",
        graphButton: "(Click on the chart to see the value)",
        yourConsumption: "Last Consumption",
        units: "SCM"
    },
    comparison: {
        unit: "SCM",
        comparison: "Comparison",
        headerContext: "Compare your daily, weekly & monthly consumption to keep a tab on gas usage",
        today: "Today",
        inProgress: "In Progress",
        consumption: "Consumption",
        yesterday: "Yesterday",
        weekly: "Weekly",
        comparison: "Comparison",
        graphButton: "(Click on chart to see the value)",
        lable1: "Last Week Consumption (SCM)",
        lable2: "Current Week Consumption (SCM)",
        monthly: "Monthly",
        units: "SCM"
    },
    history: {
        header: "Historic Consumption",
        headerContext: "Historic consumption details on your finger tips",
        custom: "Custom",
        start: "Start",
        end: "End",
        startDate: "Start Date",
        endDate: "End Date",
        date: "Date",
        legend: "Note: Please select the End Date from 01-31 days",
        submit: "Submit",
        customLegend: "X-axis Days and Y-axis",
        today: "Today",
        week: "Week",
        month: "Month",
        year:"Year",
        legend1: "X-axis Hours and Y-axis",
        legend2: "X-axis Days and Y-axis",
        legend3: "X-axis Months and Y-axis",
        legend4: "X-axis Years and Y-axis",
        graphButton: "(Click on chart to see the value)",
        total: "Total",
        consumption: "Consumption",
        average: "Average",
        units: "SCM",
        noRecordsFound: "No Records Found",
        loading: "Loading",
    },
    prepaidBalance: {
        prepaid: "Prepaid",
        balance: "Billing",
        headerContext: "Inspect your bills and pay online",
        current: "Current",
        history: "History",
        medium: "Medium",
        low: "Low",
        high: "High",
        amount: "Amount",
        date: "Date",
        button: "Click here to Top-Up"
    },
    postpaidBalance: {
        postpaid: "Postpaid",
        balance: "Balance",
        headerContext: "Inspect your bills and pay online",
        amount: "Amount",
        consumption: "Consumption",
        units: "SCM",
        billNumber: "Bill Number",
        ca: "Consumer",
        number: "ID",
        billGenerationDate: "Bill Generation Date",
        billPaybyDate: "Bill Pay By Date",
        clickHereToPay: "Click here to Pay"
    },
    mdi: {
        maximum: "Maximum",
        demand: "Demand",
        maxDemand: "Max Demand",
        headerContext: "Are you surpassing your sanctioned demand ?",
        sanctioned: "Sanctioned",
        load: "Load",
        units: "SCM",
        monthly: "Monthly",
        barGraphInfo: "(Click on chart to see the value)",
        legend: "Monthly Maximum Demand Indicator",
        graphButton: "Click here to view Current Month's MDI Chart",
        recorded: "Recorded",
        spikeMd: "Spike MD",
        logDate: "Log Date",
        pmd: "P-MD",
        amd: "A-MD",
        voltage: "Voltage",
        tableFooter: "A-MD - Assigned MD, P-MD - Peak MD",
        // Horizontal Graph
        maximumDemandReached: 'Maximum Demand Reached (kW)',
        assignedMaximumDemand: 'Assigned Maximum Demand (kW)',
    },
    powerQuality: {
        power: "Power",
        quality: "Quality",
        headerContext: "How is the quality of power that you are receiving ?",
        peak: "Peak",
        voltage: "Voltage",
        hourlyTrend: "Hourly Trend",
        legend: "Voltage Spikes for last 7 Hours",
        dataTable: "Data Table",
        graph: "Graph",
        logHour: "Log Hour",
        freq: "Freq",
        md: "MD",
        tableFooter: "MD - Maximum Demand, Freq - Frequency"
    },
    eventAnalysis: {
        event: "Event",
        analysis: "Analysis",
        headerContext: "Your smart meter can detect events related to power quality",
        selectParameter: "Select Parameter",
        category: "Category",
        make: "Make",
        selection: "Selection",
        daily: "Daily",
        monthly: "Monthly",
        yearly: "Yearly",
        month: "Month",
        year: "Year",
        period: "Peroid",
        duration: "Duration",
        startDate: "Start Date",
        endDate: "End Date",
        submit: "Submit",
        cancel:"Cancel",
        recorded: "Recorded",
        events: "Events",
        date: "Date",
        eventName: "Event Name",
        count: "Count",
        voltage: "Voltage",
        loadingDropdown: "Loading Dropdown",
        loading: "Loading",
    },
    energyTips: {
        energy: "Energy",
        savingsTips: "Savings Tips",
        tip: "Tip",
        headerContext: "Simple methods can help you save a significant amount of energy",
        saving: "Saving",
        guidelines: "Guidelines"
    },
    faqs: {
        top: "Top",
        questions: "Questions",
        haveQueries: "Have Queries ?",
        all: "All",
        general: "General",
        billing: "Billing",
        category: "Category"
    },
    notifications: {
        be: "Be",
        notified: "Notified",
        headerContext: "Engage with the Utility via notifications",
        notifications: "Notifications",
        noNotificationMessage: "You have no New Notifications available at this moment. Please check again later",
        clear: "Clear"
    },
    energyCostCalc: {
        energy: "Energy",
        costCalculator: "Cost Calculator",
        headerContext: "Adding a new appliance ? Analyse its energy needs",
        didYouKnow: 'Did you know ?',
        didYouKnowContent: 'Refrigeration takes 1200 Watts a day. Which cost 4000 INR per year.',
        // Step 1
        fillDetails: "FILL DETAILS",
        analysis: "ANALYSIS",
        results: "RESULTS",
        fillThe: "Fill the",
        details: "Details",
        product: "Product",
        category: "Category",
        select: "Select",
        productAge: "Product Age",
        greenStartRating: "Green Star Rating (if any)",
        next: "Next",
        // Step 2
        confirm: "Confirm",
        consumption: "Consumption",
        watts: "Watts",
        timeFrame: "Time Frame",
        hoursDays: "5 Hours/Day",
        rate: "Rate",
        back: "Back",
        calculate: "Calculate",
        // Step 3
        daily: "Daily",
        monthly: "Monthly",
        yearly: "Yealry",
        costing: "Costing",
        forecasted: "Forcasted",
        bill: "Bill",
        month: "Month",
        goBack: "Go Back",
        // Next Screen
        typical: "Typical",
        householdAppliance: "Household Appliance",
        householdApplianceContent: "Please select the account you want to login or add a different account",
        clickHere: "Want to know more? Click here >",
        search: "Search",
        general: "General",
        lightning: "Lightning"
    },
    support: {
        header1: "How can i help",
        header2: "today ?",
        search: "Search",
        general: "General",
        category: "Category",
        image: "Image",
        info1 : [
            { name: 'BILL PAYMENT', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
            { name: 'CONTACT US', url: require('SmartgasConsumerApp/assets/animations/profile.json') },
            { name: 'ABOUT US', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
            { name: 'LOCATION', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
        ],
        info2 : [
            { name: 'SMART BIJULEE', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
            { name: 'SERVICE GUIDE', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
        ],
        info3 : [
            { name: 'LIVE CHAT', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
            { name: 'CONSERVATION', url: require('SmartgasConsumerApp/assets/animations/payment.json') },
        ]
    },
    checkPrograms: {
        search: "Search",
        upcomingProgram: "Upcoming Program",
        headerContext: "Energy saving programs",
        period: "Period",
        duration: "Duration",
        submit: "Submit",
        program: "Program",
        list: "List",
        secondScreenHeaderContext: "Energy saving programs",
        date: "Date",
        savings: "Savings",
        thirdScreenHeaderContext: "Your energy saving programs",
        episodeInformation: "Episode Information",
        eventCategory: "সংঘটনাৰ শ্ৰেণী",
        expectedSavings: "Expected Savings",
        startDate: "Start Date",
        endDate: "End Date",
        duration: "Duration",
        showInterest: "Show Interest",
        //Upcomming Events
        thankYouForShowingthe: "Thank you for showing the",
        interest: "Interest",
    },
    myPrograms: {
        myPrograms: "My Programs",
        plmdr: "PLMDR",
        headerContext: "Your energy saving programs",
        pastEvents: "Past Events",
        upcomingEvents: "Upcomming Events",
        date: "Date",
        savings: "Savings",
        search: "Search",
        upcomingProgram: "Upcoming Program",
        headerContext: "Energy saving programs",
        period: "Period",
        duration: "Duration",
        submit: "Submit",
        program: "Program",
        list: "List",
        secondScreenHeaderContext: "Energy saving programs",
        date: "Date",
        savings: "Savings",
        // Past Events
        programCategory: "Program Category",
        pastHeaderContext: "Save Energy Day",
        congratulations: "Congratulations",
        youHaveSavedSuccessfully: "You have saved successfully",
        withThe: "with the",
        energySaving: "Energy Saving",
        event: "Event",
        youHave: "You have",
        succesfully: "succesfully",
        been: "been",
        unsubscribed: "unsubscribed",
        fromTheEvent: "from the event",
        // Upcomming Events
        thirdScreenHeaderContext: "Your energy saving programs",
        episode: "Episode",
        information: "Information",
        episodeInformation: "Episode Information",
        eventCategory: "Event Category",
        engerySaving: "Energy Saving",
        mySavings: "My Savings",
        expectedSavings: "Expected Savings",
        startDate: "Start Date",
        endDate: "End Date",
        duration: "Duration",
        noMoreInterest: "No More Interest",
    },
    netMetering: {
        net: "Net",
        metering: "Metering",
        headerContext: "Know your credits from your solar energy system",
        savings: "Savings",
        utilization: "Utilization",
        today: "Today",
        week: "Week",
        month: "Month",
        HPSEBInput: "Azeriqas Input",
        mySolarOutput: "My Solar Output",
        units: "SCM"
    },
    schemes: {
        HPSEB: "Azeriqas",
        schemes: "Schemes",
        search: "Search",
        headerContext: "Click on title to redirect to specific page to know more information",
        copyright: " Copyright @ 2023 - Esyasoft"
    },
    settings: {
        settings: "Settings",
        // Profile Settings
        profile: "Profile",
        information: "Information",
        PIContent: "Name, Email",
        manage: "Manage",
        multipleAccount: "Multiple Accounts",
        MMAContent: "Switch Accounts",
        change: "Change",
        password: "Password",
        CPContent: "Change your current password",
        // App Settings
        app: "App",
        color: "Color",
        mode: "Mode",
        CMContent: "To change the app view to light/dark",
        language: "Language",
        CLContent: "To change language",
        user: "User",
        management: "Management",
        UMContent: "To add Family Members",
        // General Settings
        general: "General",
        rateOur: "Rate Our",
        ROAContent: "Rate & Review the application",
        send: "Send",
        feedback: "Feedback",
        SFContent: "Share your thought to Smartgas",
        terms: "Terms and",
        conditions: "Conditions",
        TCContent: "Read our privacy policies & T/C"
    },
    profile: {
        sanctionedLoad: "Sanctioned Load",
        serviceDate: "Service Date",
        merterServiceNumber: "Meter Serial Number",
        contactNumber: "Contact Number",
        emailId: "Email Id",
        caNo: "Consumer ID",
    },
    multipleAccounts: {
        manage: "Manage",
        multipleAccounts: "Multiple Accounts",
        headerContext: "Add here your different accounts linked with your same mobile number",
        listOf: "List of",
        accountsHandled: "Accounts Handled",
        slNo: "Sl No",
        name: "Name",
        caNo: "Consumer ID",
        action: "Action",
        tableFooter: "You can add upto 20 Account Members",
        // Switch
        switchAccount: "Switch Account",
        switchAccountMessage: "Do you want to switch Account to User",
        ok: "Okay",
        cancel: "Cancel",
        // Delete
        deleteHeader: "Delete Account",
        deleteMessage: "Do you want to Delete Account to User",
        deleteSuccess: "Account Deleted Successfully",
        // Create
        createHeader: "Info",
        createMessage: "Added Member with Consumer ID",
        createSuccessfully: "Successfully",
        // Swtich Account Messages
        message1: "Initialising Account Switch....",
        message2: "Changing to",
        message3: "Finalizing....",
        message4: "Refreshing Application....",
        generateOtp: "Generate OTP",
        consumerNumber: "Consumer ID",
        consumer: "Consumer",
        number: "ID",
        enter: "Enter",
        mobileNumber: "Mobile Number",
        submit: "Submit",
        otp: "OTP"
    },
    changePassword: {
        reset: "Reset",
        caNo:"Consumer ID",
        password: "Password",
        headerContext: "Please change your password every three months for your account safety and security",
        currentPassword: "CURRENT PASSWORD",
        newPassword: "NEW PASSWORD",
        confirmPassword: "CONFIRM PASSWORD",
        submit: "Submit"
    },
    colorMode: {
        change: "Change",
        colorMode: "Color Mode",
        headerContext: "Change Color Mode between light and dark as per your interest",
        lightMode: "Light Mode",
        info: "Click the button to enable",
        darkMode: "Dark Mode",
        message1: "Initialising Color Mode....",
        changeToDarkMode: "Changing to Dark Mode",
        changeToLightMode: "Change to Light Mode",
        message3: "Finalizing....",
        message4: "Refreshing Application",
    },
    language: {
        change: "Change",
        language: "Language",
        headerContext: "Select between your regional language Assamese and English to view the App.",
        languageType: "English",
        selectedLanguage: "Selected Language",
        chooseLanguage: "Select Language",
        message1: "Initialising Language....",
        message2: "Setting up new Language....",
        message3: "Finalizing....",
        message4: "Refreshing Application",
    },
    userManagement: {
        user: "User",
        management: "Management",
        headerContext: "You can share your account with your family members with limited access",
        listOf: "List of",
        members: "Members",
        name: "Name",
        contactNo: "Contact No",
        link: "Link",
        action: "Action",
        tableFooter: "You can add upto 5 Family Members",
        fillDetails: "FILL DETAILS",
        analysis: "ANALYSIS",
        results: "RESULTS",
        // Step 1
        fillThe: "Fill the",
        details: "Details",
        name: "Name",
        contactNumber: "Contact Number",
        mobileNumberError: "Please enter the correct Mobile Number",
        relation: "Relation",
        select: "Select",
        master: "Master",
        family: "Family",
        tenant: "Tenant",
        next: "Next",
        // Step 2
        confirmThe: "Confirm the",
        back: "Back",
        // Step 3
        sendThe: "Send the",
        invitationLink: "Invitation link",
        feedbackContext: "Hey, the app is fabulous.. Especially the design",
        send: "Send",
        congratulations: "Congratulations",
        inviteInfo: "Your invitation has been succesfully sent to",
        inviteFooter: "Visit www.esyasoft.com, for further instructions",
        done: "Done"
    },
    feedback: {
        speakYour: "Speak Your",
        mind: "Mind",
        // headerContext: "Please provide us your Review, for us to serve you better.",
        headerContext: "Please provide your feedback, it will help us to serve you better.",
        // Step 1
        howWasYour: "How was your",
        experience: "Experience",
        next: "Next",
        sad: "Sad",
        neutral: "Neutral",
        happy: "Happy",
        // Step 2
        whatMadeYou: "What made you",
        // questionAnswer: "",
        happyoption1: "Clarity of Info",
        happyoption2: "Ease of Navigation",
        happyoption3: "Overall look & feel",
        back: "Back",
        // Step 3
        feedback: "Write your feedback in less than 200 words",
        submit: "Submit",
        thankYouForSharing: "Thank you for sharing",
        your: "your",
        thanksFooter: "Visit www.esyasoft.com for more information",
        footer: "A Smart Initiative by Esyasoft."
    },
    termsAndConditions: {
        termsAnd: "Terms And",
        conditions: "Conditions",
        general: "GENERAL",
        information: "INFORMATION",
        data: "DATA",
        sources: "SOURCES"
    },
    contactUs: {
        getIn: "Have a",
        touch: "query ?",
        headerContext: "Get your Queries resolved.",
        customerCare: "Customer Care",
        emailId: "Email Id",
        website: "Website",
        socialMedia: "Social Media",
        footer: "esyasoft All copy rights reserved"
    },
    drawer: {
        caNo: "Consumer ID",
        logout: "Log out"
    },
    logout: {
        alert: "Alert",
        message: "Are you sure you want to logout ?",
        yes: "Yes",
        no: "No"
    },
    back: "Back",
    connectivityHeader: 'No internet connectivity detected.',
    connectivitybody1: 'Please check your Network',
    connectivitybody2: 'Settings and Try Again.',

}
