export const hindi = {
    language:'English',
    hello: "Hello",
    welcome: "Welcome",
    today: "Today",
    your: "Your",
    light: "Light",
    dark: "Dark",
    english: "English",
    hindi: "Hindi",
    state: "Bangalore",
    selectedLanguage: 'Selected Language',
    back: 'Back',
    week: 'Week',
    month: 'Month',
    lastMonthConsumption: 'Last Month Consumption',
    monthlyConsumption: 'Monthly Consumption',
    monthlyForecast: 'Monthly Forecast',
    units: 'Units',
    number: 'Number',
    yourConsumption: 'Your Consumption',
    soFarToday: 'So far today.',
    // ENERGY TIPS
    energy: 'Energy',
    savingsTips: 'Savings Tips',
    energyTipsHeaderContent: 'Please go through the graph or table or anything as per your interest etc,.',
    saving: 'Saving',
    guidelines: 'Guidlines',
    // FAQs
    top: 'Top',
    questions: 'Questions',
    billing: 'Billing',
    calculations: 'Calculations',
    outage: 'Outage',
    webApp: 'WebApp',
    general: 'General',
    category: 'Category',
    // SETTINGS
    settings: 'Settings',
    profile: 'Profile',
    information: 'Information',
    PIContent: 'Name, Email, Security',
    manage: 'Manage',
    multipleAccount: 'Multiple Account',
    MMAContent: 'Switch Accounts',
    change: 'Change',
    password: 'Password',
    CPContent: 'Change your current password',
    app:'App',
    settings: 'Settings',
    color: 'Color',
    mode: 'Mode',
    CMContent: 'To change the app view to light',
    sLanguage: 'Language',
    CLContent: 'To change language',
    updates: 'Updates',
    UContent: 'Update the app from Google Play',
    user: 'User',
    managenment: 'Management',
    UMContent: 'To add Family Members',
    //energy line 25
    savingProgram: 'Saving Program',
    ESPContent: 'Join the program to Save Energy',
    //general line 37
    //settings line 40
    rateOur: 'Rate our',
    //app line 50
    ROAContent: 'Rate & Review the application',
    send: 'Send',
    feedback: 'Feedback',
    SFContent: 'Share your thought to SBPDCL',
    complaints: 'Complaints',
    CContent: 'Raise a Complaint ticket',
    terms: 'Terms &',
    conditions: 'Conditions',
    TCContent: 'Read our privacy policies & T/C',
    // PROFILE
    gender: 'Gender',
    dob: 'Date of Birth',
    contactNumber: 'Contact Number',
    emailid: 'Email Id',
    update: 'Update',
    // CHANGE/RESET PASSWORD
    reset: 'Reset',
    //password line 48
    RPContent: 'You would be logged out from all your mobile devices immediately',
    currentPassword: 'CURRENT PASSWORD',
    newPassword: 'NEW PASSWORD',
    confirmPassword: 'CONFIRM PASSWORD',
    submit: 'Submit',
    // COLOR MODE
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    CMBody: 'Click the button to enable',
    // TERMS & CONDITION
    // terms line 75 condition line 76
    // general line 37 information line 42
    data: 'DATA',
    sources: 'SOURCES',
    // MDI
    maximum: 'Maximum',
    demand: 'Demand',
    mdiContent: 'Please go through the graph or table or anything as per your interest etc,.',
    assigned: 'Assigned',
    maxDemand: 'Max Demand',
    monthly: 'Monthly',
    clickToEnlarge:'click to Enlarge',
    lastWeekConsumption: 'Last Week Consumption',
    currentWeekConsumption: 'Current Week Consumption',
    recorded: 'Recorded',
    spikeMd: 'Spike MD',
    // DRAWER
    dashboard: 'Dashboard',
    MDI: 'MDI',
    powerQuality: 'Power Quality',
    eventAnalysis: 'Event Analysis',
    energyTips: 'Energy Tips',
    faq: 'FAQ',
    notification: 'Notification',
    energyCostCalc: 'Energy Cost Calc',
    support: 'Support',
    // settings line 40
    HPSEBPlus: 'SBPDCL +',
    // complaints line 70,
    logout: 'Logout',
    // MD Graph
    maximumDemandReached: 'Maximum Demand Reached (Units)',
    assignedMaximumDemand: 'Assigned Maximum Demand (Units)',
    mdgraph: 'MD Graph',
    // POWER QUALITY
    power: 'Power',
    quality: 'Quality',
    PQHeaderContent: 'Please go through the graph or table or anything as per your interest etc,.',
    peak: 'Peak',
    voltage: 'Voltage',
    vol: 'Voltage',
    hourly: 'Hourly',
    trend: 'Trend',
    PQFooterTable: 'MD - Maximum Demand, Freq - Frequency',
    PQFooterGraph: 'Voltage Spikes for last 7 Hours in Vol (v)',
    dataTable: 'Data Table',
    graph: 'Graph',
    share: 'Share',
    // Event Analysis
    event: 'Event',
    // notification line 120
    EAContent: 'Please go through the graph or table or anything as per your interest etc,.',
    // category line 38
    period: 'Period',
    duration: 'Duration',
    sampling: 'Sampling',
    freq: 'Freq',
    daily: 'Daily',
    yearly: 'Yearly',
    // submit line 91
    // recorded line 111
    events: 'Events',
    // UNIT COMPARISON
    unit: 'Unit',
    comparison: 'Comparison',
    UCContent: 'Please go through the graph or table or anything as per your interest etc,.',
    around: 'Around',
    you: 'You',
    monthlyComparison: 'Monthly Comparison',
    neighbour: 'Neighbour',
    global: 'Global',
    bi: 'Bi',
    // monthly line 107
    inProgress: 'Inprogress',
    // units line 20
    // today line 5
    yesterday: 'Yesterday',
    consumption: 'Consumption',
    weekly: 'Weekly',
    watts: 'Watts',
    // HISTORY
    historyHeader: 'Historic Electricity Consumption',
    historyContent: 'Please go through the graph or table or anything as per your interest etc,.',
    custom: 'Custom',
    // today line 5
    // week line 15
    // month line 16
    set: 'Set',
    frequency: 'Frequency',
    start: 'Start',
    date: 'Date',
    end: 'End',
    // submit line 91
    total: 'Total',
    average: 'Average',
    // PAY MY BILL
    pay: 'Pay',
    myBill: 'My Bill',
    payMyBillContent: 'Please go through the graph or table or anything as per your interest etc,.',
    amount: 'Amount',
    // consumption line 174
    compare: 'Compare',
    last: 'Last',
    // month line 16
    savings: 'Savings',
    // energy line 25
    tips: 'Tips',
    PMBFooterHeader1: 'Reducing heating usage in the winter',
    PMBFooterHeader2: 'Changing to energy efficient light bulbs',
    PMBFooterHeader3: 'Fix that leaky faucet',
    PMBFooterBody1: 'Set your thermostat to 70 C or lower when your in home or away.',
    PMBFooterBody2: 'Lightning makes up about 5% of your total usage in your home.',
    PMBFooterBody3: 'Fixing a hot water leak in your faucet can save upto 80% power per year.',
    // BILLING HISTORY
    payment: 'Payment',
    history: 'History',
    billingHistoryContent: 'Please go through the graph or table or anything as per your interest etc,.',
    // consumption line 174
    // amount line 196

    // FEEDBACK
    speak: 'Speak',
    // your line 6
    mind: 'Mind',
    FeedbackContent: 'Please go through the graph or table or anything as per your interest etc,.',
    how: 'How',
    was: 'was',
    yourLowerCase: 'your',
    experience: 'Experience',
    next: 'Next',
    // back line 13
    what: 'What',
    made: 'made',
    youLowerCase: 'you',
    happy: 'Happy',
    happyoption1: 'Clarity of Info',
    happyoption2: 'Ease of Navigation',
    happyoption3: 'Overall look & feel',
    // submit line 91
    thank: 'Thank',
    for: 'for',
    sharing: 'sharing',
    visit: 'Visit',
    more: 'more',
    feedbackFooter: 'Initivative by SBPDCL Technologies',
}
